name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Build Docker image
        run: docker build -t github-actions-demo .

      - name: Run Docker container
        run: docker run -d --name github-actions-demo -p 5000:5000 github-actions-demo

      - name: Check container
        run: docker ps -a

      - name: Check container logs
        run: docker logs github-actions-demo

      - name: Test application
        run: curl -v http://localhost:5000


  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/github-actions-demo

            echo "Pulling latest code..."
            git pull origin main

            echo "Removing old container..."
            docker rm -f github-actions-demo || true

            echo "Building new Docker image..."
            docker build -t github-actions-demo .

            echo "Starting new container..."
            docker run -d \
              --name github-actions-demo \
              -p 5000:5000 \
              github-actions-demo

            echo "Checking container..."
            docker ps

            echo "Checking application..."
            curl -v http://localhost:5000
